export const GET_DATA_BEGIN = 'GET_DATA_BEGIN';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const CHECK_BREAKPOINT = 'CHECK_BREAKPOINT';

export const GET_STORIES_BEGIN = 'GET_STORIES_BEGIN';
export const GET_STORIES_ERROR = 'GET_STORIES_ERROR';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_UPDATE_BEGIN = 'GET_STORIES_UPDATE_BEGIN';
export const GET_STORIES_UPDATE_ERROR = 'GET_STORIES_UPDATE_ERROR';
export const GET_STORIES_UPDATE_SUCCESS = 'GET_STORIES_UPDATE_SUCCESS';
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
