export const GET_DATA_BEGIN = 'GET_DATA_BEGIN';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const CHECK_BREAKPOINT = 'CHECK_BREAKPOINT';
